export const calculators = {
  "juros-compostos": {
    title: "Calculadora de juros compostos",
    shortTitle: "Juros compostos",
    description: "Simule juros compostos com aportes mensais, taxa mensal ou anual. Compare o total investido e o patrimônio projetado em uma calculadora gratuita.",
    intro: "Transforme tempo e constância em uma projeção. Ajuste os valores e acompanhe o efeito dos aportes no seu patrimônio.",
    guide: "/conteudos/juros-compostos",
    explanation: "A simulação aplica os juros ao saldo de cada mês e acrescenta o aporte ao final do período. A taxa anual é convertida para uma taxa mensal equivalente. O patrimônio final reúne o valor inicial, os aportes e os juros acumulados.",
    assumptions: "A taxa permanece constante. Impostos, taxas e inflação não são descontados automaticamente. Os resultados são cenários ilustrativos, não uma promessa de rentabilidade.",
    steps: ["Informe seu valor inicial e o aporte mensal.", "Escolha a periodicidade da taxa e preencha o prazo correspondente.", "Compare os resultados e consulte a evolução mês a mês."],
    cta: "Quanto cabe de aporte no seu mês?",
    ctaDescription: "Organize entradas e despesas no orçamento doméstico para planejar seus aportes com base na sua rotina.",
  },
  "reserva-emergencia": {
    title: "Calculadora de reserva de emergência",
    shortTitle: "Reserva de emergência",
    description: "Calcule uma estimativa de reserva de emergência a partir dos seus gastos mensais e perfil de trabalho. Simule gratuitamente e planeje sua meta.",
    intro: "Dê um número à sua tranquilidade. Estime uma reserva a partir dos seus gastos e do seu perfil de trabalho.",
    guide: "/conteudos/reserva-de-emergencia",
    explanation: "O cálculo multiplica o gasto mensal informado pela quantidade de meses definida no cenário: 6 meses para CLT, 12 para PJ e 3 para funcionário público. Esses valores são premissas desta calculadora e podem não refletir sua necessidade individual.",
    assumptions: "Dependentes, estabilidade da renda e despesas variáveis essenciais também influenciam a meta. A simulação não inclui rendimento da reserva nem substitui a avaliação do seu orçamento.",
    steps: ["Selecione o perfil de trabalho para definir o cenário.", "Informe o gasto mensal que deseja cobrir.", "Confira a meta estimada e revise se ela representa sua realidade."],
    cta: "Sua reserva merece acompanhamento.",
    ctaDescription: "No aplicativo de orçamento, acompanhe a meta, as alocações, os aportes e as retiradas da sua reserva de emergência.",
  },
  "financiamento-price-sac": {
    title: "Calculadora de financiamento SAC e Price",
    shortTitle: "Financiamento SAC × Price",
    description: "Compare financiamento SAC e Price: parcelas, juros totais e saldo devedor. Simule valor financiado, prazo e CET mensal ou anual gratuitamente.",
    intro: "Veja o impacto de cada parcela antes de decidir. Compare os dois sistemas com os mesmos valores e prazo.",
    guide: "/conteudos/sac-x-price",
    explanation: "Na tabela Price, a prestação é constante neste modelo. No SAC, a amortização é constante e as prestações diminuem ao longo do prazo. A comparação usa o mesmo valor financiado, número de parcelas e taxa mensal equivalente.",
    assumptions: "O CET informado é tratado como taxa efetiva constante. A simulação não reproduz cobranças específicas, indexadores ou seguros variáveis de um contrato real. Confira as condições da instituição financeira.",
    steps: ["Informe o valor a financiar e a quantidade de parcelas.", "Preencha o CET e selecione se a taxa é mensal ou anual.", "Compare o total pago, as parcelas e o saldo devedor."],
    cta: "Essa parcela cabe no seu orçamento?",
    ctaDescription: "Compare seu compromisso com as entradas, os gastos e as contas a pagar no aplicativo de orçamento doméstico.",
  },
  aposentadoria: {
    title: "Calculadora de aposentadoria",
    shortTitle: "Aposentadoria",
    description: "Simule quanto investir por mês para sua aposentadoria. Informe idade, patrimônio atual, meta e taxa estimada para projetar seus aportes.",
    intro: "Aproxime seu plano de futuro da realidade de hoje. Descubra o aporte mensal estimado para a sua meta.",
    guide: "/conteudos/aposentadoria",
    explanation: "A calculadora usa a diferença entre a idade atual e a idade de aposentadoria para obter o prazo em meses. A partir do patrimônio atual, da meta e da taxa informada, estima aportes constantes ao final de cada mês.",
    assumptions: "Use uma taxa real se quiser trabalhar com poder de compra atual: a inflação não é descontada automaticamente. A projeção não inclui impostos, taxas ou a fase de retiradas na aposentadoria.",
    steps: ["Informe as idades atual e desejada para aposentadoria.", "Preencha patrimônio atual, meta e taxa estimada.", "Veja o aporte mensal e compare diferentes cenários."],
    cta: "Um plano de futuro começa no mês atual.",
    ctaDescription: "Acompanhe seu orçamento para entender quanto consegue separar de forma consistente para seus objetivos.",
  },
} as const;
export type CalculatorSlug = keyof typeof calculators;
